### ISSUE TITLE
[iCubDarmstadt01] torso joint no. 2 is unstable at 0.0 degree

### ISSUE THREAD

**Issue by giuliavezzani** [tacman-fp7/handover#21]
If we want the torso not to move, we need to put the torso joint equal to -5.0 (or any values different from zeros).

**Comment by pattacini** [comment]
See https://github.com/robotology/QA/issues/147

**Comment by giuliavezzani** [comment]
Fixed. See [icub-support #370](https://github.com/robotology/icub-support/issues/370) for more details.
