### ISSUE TITLE
Allow the execution of the stable grasp on both hands at the same time

### ISSUE THREAD

**Issue by massimoregoli** [tacman-fp7/handover#23]
At the moment the stable grasp can be run only on one hand at a time to avoid conflicts between ports. Change the code in order to allow its execution on both hands at the same time, as needed for the handover task.

**Comment by massimoregoli** [comment]
Now two instances of the stable grasp module (one for the left hand and one for the right hand) can be run at the same time. See [here](https://github.com/tacman-fp7/handover/wiki/Stable-grasp-module-interface) for more details.

**Comment by pattacini** [comment]
Well done @massimoregoli 

Also, I've seen you provided the documentation. Normally, this kind of info should accompany the code itself, as done for example in [**how-to-document-modules**](https://github.com/robotology/how-to-document-modules) 😉

**Comment by pattacini** [comment]
Ah ok, it's a partial documentation for the specific task.
Great then!

**Comment by massimoregoli** [comment]
Yes exactly it is specific :blush:
