### ISSUE TITLE
hand removal from point cloud and filtering

### ISSUE THREAD

**Issue by giuliavezzani** [tacman-fp7/handover#3]

**Comment by giuliavezzani** [comment]
Even if hand removal from point cloud is executed by simply discarding "grayish"  points (points that satisfy R=G=B values), the filtered point cloud are very good:

Point cloud filtered with **hand filter**:


![point-cloud](https://cloud.githubusercontent.com/assets/9597070/19969247/35f7e62a-a1d8-11e6-86da-d168b6e4f803.jpeg)


Point cloud filtered with **gray filter** and **spatial filter**:


![point-cloud-filtered](https://cloud.githubusercontent.com/assets/9597070/19969269/4c1e0862-a1d8-11e6-961b-f59e600b1d22.jpeg)

**Comment by giuliavezzani** [comment]
**Volume filter**, i.e. the filter who selects only points inside a ciylinder inside the three finger positions, must be tested more in detail.

**Comment by pattacini** [comment]
Quite impressive results 😃

**Comment by giuliavezzani** [comment]
**Volume filter to be re-designed**.

I tested some particular cases such as:

![fingers](https://cloud.githubusercontent.com/assets/9597070/20064996/d3af6e38-a50c-11e6-8744-b7a8c1ae6e60.png)


where the fingers are very close among each others.
In this case, the best computed circle has centere in the origin of the hand reference frame, instead of being a small circle bounded by the finger positions.
However, if the small circle had been computed, too many points would have been discarded.
It's better to understand how to **change volume filter or to adapt it** to the objects under consideration, if volume filter is really necessary.

**Comment by giuliavezzani** [comment]
Added **ellips filter**: it's similar to **volume filter** but instead of reconstructing a sphere, we reconstruct a ellipsoid passing by the thumb, index and palm positions.
In this way we have more degrees of freedom: two axis lengths and  two different offsets.

**Comment by giuliavezzani** [comment]
A new code structure has been designed and has being tested in these days.  An outline of the code structure is given by:

![code-structure](https://cloud.githubusercontent.com/assets/9597070/20181716/8aeb0b8a-a75f-11e6-80d6-e57a232c3880.png)


Two modalities are available:
- **online**: the point cloud and the kinematic information are collected on the robot (or on the simulator) and the filtered points are sent to the localization module
- **offline**: the points are read from files and the filtered points are saved into a new file.

All points and results can be:
- **saved** in files
- **sent** through `thrift` service

Various option are available. Parameters and functionalities can be set and asked through `rpc port.` See `doxygen` documentation for more information [**to do**].

**Comment by giuliavezzani** [comment]
**New thrift services** added to the new code structure. Code is now ready for a **intensive test** on the robot, in order to find (possibly) **final parameters** for filters.
