### ISSUE TITLE
Preparation for the final demo

### ISSUE THREAD

**Issue by giuliavezzani** [tacman-fp7/handover#33]
This is to organize the final rush for the demo.

**Comment by giuliavezzani** [comment]
## What to Do

- [x] perform **`depth2kin`** for the `right hand`
- [x] perform **`depth2kin`** for the `left hand`
- [x] check **point cloud quality** after `depth2kin`
- [x] add control on **`context`** where necessary
- [x] add **initial pose also for second arm**
- [x] add **final movement** moving the **first hand** far away -> try with waypoint ?
- [x] add gaze tracking 
- [x] automatize everything with **`lua`**
- [x] find good parameters for **approach**
- [x] check on number of measurements in `localizer`
- [x] set **`trajectory time`** everywhere

**Comment by giuliavezzani** [comment]
## One of the first  accomplished handover

[Here](https://www.youtube.com/watch?v=rGU-uDTCyGw) you can find a link to a video showing one of the first accomplished handovers.

So far:
- the `gaze interface` has been introduced to look at the hand poses
- several `rpc commands` are available to have nice poses at the beginning and the end and to play with the task

This is a good starting point :tada:

**Comment by lornat75** [comment]
Well done!

**Comment by giuliavezzani** [comment]
Here are other two (older) examples of handover:

- from the [right to the left hand](https://www.youtube.com/watch?v=2mDyMMvsGx8)
- from the [left to the right hand](https://www.youtube.com/watch?v=qbxKlZ2L0SE)

but without any gaze control.

**Comment by giuliavezzani** [comment]
## Handover RtoL (Right to Left arm) Tests with  sugar box

I found a good initial position and the following parameters for performing **5/7 successful handovers**, using every time a different point cloud and estimated pose.

[Here](https://www.youtube.com/watch?v=ROMM2G-a6ZY) you can find the related video.

The method seems to be quite robust for the same initial pose, even if no compensation between kinematics and vision is performed.


The parameters are the following:

- `acqusition poses right`  joints :+1: 
```
-61.0 48.0 50.1 40.0  -31.0  17.0 18.0 
```
- `fixate point`:
```
y-= -0.18
z+= 0.15
```
- `offset_x_final`=0.03
- `offset_z_final`=0.0
- `offset_x_approach=0.08`
- `offset_z_approach=0.04`

**Comment by lornat75** [comment]
👍

**Comment by giuliavezzani** [comment]
Unfortunately, it's very difficult to have some generic and robust in very different situations, because of the strong non-linear offset between kinematics and vision ...
