### ISSUE TITLE
Handover with 4 objects

### ISSUE THREAD

**Issue by giuliavezzani** [tacman-fp7/handover#36]
This is to summarize the work for the paper

**Comment by giuliavezzani** [comment]
Hereafter, I summarize the results obtained with **4 objects** for some main steps of the handover:

1. **point cloud** acquisition
2. object **localization**
3. **pose selection**
4. **kinematics-vision** offset compensation

## Objects taken into account:

1. Domino box
2. Jello box
3. Pringles tube
4. Mustard box

**Note** I focus on this bigger objects. If possible, I'll try to make the handover work also with the small red cup and the tomato soup.

## Annotated models
- 8 poses for object 1,2 and 4
- 24 poses for object 3 (due to the higher number of simetry axes)

## Point cloud & Estimated object poses 

![domino-loc](https://cloud.githubusercontent.com/assets/9597070/23906231/a4397c14-08cd-11e7-9df5-6e69345ff28c.png) 
![jello-loc](https://cloud.githubusercontent.com/assets/9597070/23906214/9ca57ec6-08cd-11e7-9bf8-b6a0b40a06b2.png)
![pringles-loc](https://cloud.githubusercontent.com/assets/9597070/23906199/94078660-08cd-11e7-881d-01ee6a06cb37.png)
![mustard-loc](https://cloud.githubusercontent.com/assets/9597070/23906192/90071152-08cd-11e7-869b-cee54f3ca167.png)

## Pose Selection
### Domino box, pose 1
![domino-pose](https://cloud.githubusercontent.com/assets/9597070/23906370/10526bae-08ce-11e7-819f-45f51f9e9365.png)

### Domino box, pose 2
![domino-pose-2](https://cloud.githubusercontent.com/assets/9597070/23906379/1654fbc0-08ce-11e7-808c-3213b0ad281a.png)

### Jello box 
![jello-pose-2](https://cloud.githubusercontent.com/assets/9597070/23906447/460bcdc6-08ce-11e7-925c-d47c248e4e9e.png)



### Pringles tube

![chips-pose-1](https://cloud.githubusercontent.com/assets/9597070/23906321/e41365e8-08cd-11e7-8795-0e6af4a743c1.png)

### Mustard box, pose 1
![mustard-pose-5pc](https://cloud.githubusercontent.com/assets/9597070/23906514/7b71463a-08ce-11e7-8a44-32978bce045b.png)
### Mustard box, pose 2
![mustard-pose-7pc-3](https://cloud.githubusercontent.com/assets/9597070/23906538/9106cace-08ce-11e7-854d-84d212ab13ce.png)

## Kinematics-vision offset

Main points:

- Without any compensation, the offsets are huge
- I collected **2 poses** for the domino box (one per each of the usually selected poses)
- I used these 2 poses for correct the pose for the **domino** and the **jello**
- For the domino it worked **very well**
- For the jello it worked
- I need to test it with the mustard and the pringles, as soon as the grasp of these two objects will be stable (I'm waiting the help of @massimoregoli ).

Hereafter, the tests I performed with the domino and the jello boxes:

### Domino, pose lateral

- the pose with the lower z value is the corrected one
![correct-pose-lateral-domino](https://cloud.githubusercontent.com/assets/9597070/23906764/3963e166-08cf-11e7-96eb-827c8243d26f.png)

- handover successfully achieved
![corrected-pose-lateral-dominoi-reached](https://cloud.githubusercontent.com/assets/9597070/23906822/717c0b78-08cf-11e7-8e50-a088aba7dda6.png)

### Domino, pose on the top

- the pose with the lower z value is the corrected one
![corrected-pose-top-domino](https://cloud.githubusercontent.com/assets/9597070/23906882/afc7b49a-08cf-11e7-947b-71aad6a10be1.png)
- handover successfully achieved
![corrected-pose-domino-top-reached](https://cloud.githubusercontent.com/assets/9597070/23907022/19a83916-08d0-11e7-81bb-c70845fade54.png)


### Jello

![corrected-pose-jello-reached](https://cloud.githubusercontent.com/assets/9597070/23906976/ef0e79cc-08cf-11e7-88da-668017070673.png)


# What to Do

- to test **2 poses** for kinematics-vision compensation on **mustard** and **pringles**. 
- improve **stableGrasp** for the 4 objects under consideration

**Comment by giuliavezzani** [comment]
Hereafter I report some pictures of successful handovers with 4 objects (even if **stableGrasp** still need to be improved)

## Pose Selection

### Mustard
![mustard-corr-pose-init](https://cloud.githubusercontent.com/assets/9597070/23947709/4b641ef6-0980-11e7-90e4-20c961845126.png)

![mustard-pose-lateral-2-reached](https://cloud.githubusercontent.com/assets/9597070/23947749/6c8ef902-0980-11e7-84dd-d7a72ce723a0.png)

- The same happens for the **pringles tube** (I forgot to collect an image)

## Good correction of second hand pose with the same correction Matrix
![20170315_092137](https://cloud.githubusercontent.com/assets/9597070/23948908/72ac8d9a-0985-11e7-9e7d-5b882272362a.jpg)
![20170315_091921](https://cloud.githubusercontent.com/assets/9597070/23948914/791bd3c0-0985-11e7-82d0-f34b74c031b8.jpg)
![20170314_145557](https://cloud.githubusercontent.com/assets/9597070/23948918/7bfa8302-0985-11e7-80fc-3d022f877e98.jpg)
![20170314_143455](https://cloud.githubusercontent.com/assets/9597070/23948921/7e477fc0-0985-11e7-9d4d-321d61034603.jpg)
![20170314_142913](https://cloud.githubusercontent.com/assets/9597070/23948923/810908b4-0985-11e7-9ab2-80dfe7e67f46.jpg)

![pringles](https://cloud.githubusercontent.com/assets/9597070/23949058/f8993f8e-0985-11e7-933f-6e234beb4785.png)



# Idea
I think that the successful use of a **single correction matrix** depends on the **initial pose of the first hand during point cloud acquisition**.
This idea will be tested in next tests.

**Comment by giuliavezzani** [comment]
# Tests on kinametics-vision compensation

If the initial pose is the same, **one compensation matrix** is enough and effective for all the objects.
Hereafter, you can see the corrected pose reached by the second hand for 5 objects:

![matrix_new](https://cloud.githubusercontent.com/assets/9597070/23993143/c06400a8-0a3f-11e7-8b7d-a71fa34df9dc.jpg)
![matrix_new2](https://cloud.githubusercontent.com/assets/9597070/23993147/c28da302-0a3f-11e7-9ba2-f589d0fbe0bd.jpg)
![matrix_new3](https://cloud.githubusercontent.com/assets/9597070/23993155/c5540964-0a3f-11e7-8629-f4d6a43e0c94.jpg)
![matrix_new5](https://cloud.githubusercontent.com/assets/9597070/23993160/c6fbd080-0a3f-11e7-8c09-1d362133f86b.jpg)
![matrix_new7](https://cloud.githubusercontent.com/assets/9597070/23993165/c8f1cff2-0a3f-11e7-9d1b-bdbc0f08fae1.jpg)
![matrix_new8](https://cloud.githubusercontent.com/assets/9597070/23993167/cad00988-0a3f-11e7-80de-3f5da136f65b.jpg)
![matrix_new9](https://cloud.githubusercontent.com/assets/9597070/23993170/cc5ad472-0a3f-11e7-904a-57d29c2eda20.jpg)

**Comment by lornat75** [comment]
👍

**Comment by giuliavezzani** [comment]
We managed to perform the handover with 5 objects :tada:
