### ISSUE TITLE
Train a GMM with the aim of rotating objects by changing the hand configuration

### ISSUE THREAD

**Issue by massimoregoli** [tacman-fp7/handover#8]
Train a Gaussian mixture model using stable grasps in which long objects are inclined. It will be used to change the hand configuration in order to rotate the object and facilitate the handover task

**Comment by massimoregoli** [comment]
For this task I used the left hand of the black iCub.
The new Gaussian mixture model has been trained using the following 12 objects:

![objects](https://cloud.githubusercontent.com/assets/10046589/20195881/83a9ea56-a798-11e6-87a9-622893b8081b.jpg)

I visually detected 5 stable grasps for each object (60 in total).
Differently from the GMM trained previously a few variables have not taking into consideration, so the regression schema in this case is the following:

![gmmregressionobjectrotation](https://cloud.githubusercontent.com/assets/10046589/20196241/1ae4bddc-a79a-11e6-920e-4fc6e686ea77.png)

The difference of position between the index and the middle finger has not been considered as input because it changes considerably during the object rotation and could lead to instability. 
The distal joints may also cause instability during the transition phase and for now they have not been considered.
The trained model is composed of two Gaussian components:

![gmmobjectinclinedthumbdown](https://cloud.githubusercontent.com/assets/10046589/20196610/ba4bdb7a-a79b-11e6-8b56-f9dea703ed7c.png)

The rotation of the object is caused by the actuation of the thumb abduction joint. The following plot shows how it is related to the hand aperture (the only input variable):

![thumbabduction](https://cloud.githubusercontent.com/assets/10046589/20196703/3ba0ba38-a79c-11e6-900a-0eebfe8dde5e.png)

The following video shows the GMM regression in action. The objects are rotated starting from the usual stable pose:

[![gmmregoiscreenshot](https://cloud.githubusercontent.com/assets/10046589/20213632/de21e04e-a809-11e6-9566-d8c823fb85b6.png)](https://massimo-regoli-iit.tinytake.com/sf/MTExMTIzNF80NDA2NTkx)

The objects were correctly rotated as expected. The most unstable object (the Domino box) moved a little bit during the transition.

**Comment by pattacini** [comment]
That's impressive! Very well done @massimoregoli
